INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, PARENT_CATEGORY_ID) VALUES (1, 'Electronic', 'Cool electronic things', NULL);
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, PARENT_CATEGORY_ID) VALUES (2, 'Notebooks', '', 1);
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, PARENT_CATEGORY_ID) VALUES (3, 'Mobile phones', '', 1);
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, PARENT_CATEGORY_ID) VALUES (4, 'Furniture', '', NULL);
INSERT INTO CATEGORIES (ID, NAME, DESCRIPTION, PARENT_CATEGORY_ID) VALUES (5, 'Tables', '', 4);
