INSERT INTO GOODS(ID, NAME, PRICE, DESCRIPTION, QUANTITY, MANUFACTURER, CATEGORY_ID) VALUES (1, 'Nokia 3310', 1000, 'Cool phone', 10, 'Nokia', 3);
INSERT INTO GOODS(ID, NAME, PRICE, DESCRIPTION, QUANTITY, MANUFACTURER, CATEGORY_ID) VALUES (2, 'Nexus 4', 4000, 'Android phone', 5, 'LG', 3);
